### ISSUE TITLE
Le cluster ne s'affiche pas dans le dashboard

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#1]
Pas de cluster
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/17337140/51542118-c30fe700-1e5a-11e9-858c-5ce9bbbc9f58.png">

et pourtant il est bien créé:
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/17337140/51542150-d753e400-1e5a-11e9-8dd5-72d056b37373.png">

**Comment by lionelmace** [comment]
Hmm je le vois bien... Tu as lancé un refresh du cache sur le browser?
![image](https://user-images.githubusercontent.com/12241613/51554071-a41e4e80-1e74-11e9-93eb-32c42aed4cf8.png)

**Comment by jmoliva** [comment]
Maintenant je vois çà:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/17337140/51555178-56571580-1e77-11e9-8a19-859cd45d9f5e.png">

et çà:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/17337140/51555248-82729680-1e77-11e9-9b76-eec6fa68e05d.png">

si tu n'as rien changé, c'est très bizarre

**Comment by lionelmace** [comment]
Hmmm. Tu ne devrais pas voir les RGs demo, default.

**Comment by lionelmace** [comment]
Fixed! I changed the iam permission to restrict access for Cloudant, Toolchain and Continuous Delivery to the Resource Group `lab` only. You should only see this:

![image](https://user-images.githubusercontent.com/12241613/51595309-b345e080-1ef6-11e9-8ba1-d456a80a9a4e.png)

**Comment by jmoliva** [comment]
yep c'est bon
