### ISSUE TITLE
Pb version helm sur cloudshell après avoir fait le --force-upgrade

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#13]
On se retrouve comme çà et plus possible d'utiliser helm en ligne de commande
jmoforbx2019a@cloudshell-589969b9d4-5pp7g:~$ helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
jmoforbx2019a@cloudshell-589969b9d4-5pp7g:~$ helm list
Error: incompatible versions client[v2.12.2] server[v2.8.1]

**Comment by lionelmace** [comment]
Tu as fait un helm upgrade dans le cloudshell?

**Comment by jmoliva** [comment]
Avec la mise à jour du client Helm de la pipeline à 1.12.2, y'a plus de pb, tout est homogène
