### ISSUE TITLE
Modif fin du lab CD

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#14]
Supprimer l'image de l'étape 12 et les étapes 13 et 14.
Mettre l'image à la place expliquant comment ouvrir l'URL de l'application: 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/17337140/51622037-0a1eda80-1f36-11e9-92ae-feee408929c1.png">

**Comment by lionelmace** [comment]
Done!
