### ISSUE TITLE
Fix Section 4 access

### ISSUE THREAD

**Issue by AMarti96** [lionelmace/iks-lab#17]
First, thanks for all the content from this book, it is really helpful to have a hand-on example over IKS with a running app!

The only thing I faced while reading it is that in the current state of https://lionelmace.github.io/iks-lab, there is no way to access the `LAB4` contents from the left-side navigation index.

It seems the contents of https://github.com/lionelmace/iks-lab/blob/master/book/SUMMARY.md#lab-4---devops-and-helm-charts point to the following

```
## Lab 4 - DevOps and Helm charts

* [Deploy with Helm](devops-helm.md)
* [Deploy with Continuous Delivery](devops-continuous-delivery.md)
```

But the name of those files in https://github.com/lionelmace/iks-lab/tree/master/book are `03-devops-helm.md` and `03-devops-continuous-delivery.md`.

In order to correct this, either the `SUMMARY.md` contents need to be changed or the name of the files changes to match the index.

**Comment by lionelmace** [comment]
Thank you for the report. This is now fixed.
