### ISSUE TITLE
Il faut changer de compte par défaut sur cloudshell pour voir le cluster

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#2]
si on ouvre cloudshell depuis le même browser on est déjà logué, mais avec le compte de l'utilisateur principal.
Il faut donc se reloguer et choisir le compte LionelMace
=> Etape: 2. Select an Account unless you have only one. 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/17337140/51542564-dbcccc80-1e5b-11e9-92f7-cb17fa1a0b31.png">

**Comment by lionelmace** [comment]
Oui je pense qu'il est bien que les participants fassent la manip de se loger et de choisir le compte.
