### ISSUE TITLE
Proposer d'utiliser l'éditeur intégré pour modifier les fichiers

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#5]
Au niveau de l'édition du fichier `deploy-app.yml`proposer d'utiliser l'éditeur intégré 
<img width="183" alt="image" src="https://user-images.githubusercontent.com/17337140/51544191-a2965b80-1e5f-11e9-8ba3-80ddd8f94463.png">

<img width="915" alt="image" src="https://user-images.githubusercontent.com/17337140/51544226-bb9f0c80-1e5f-11e9-8dc6-cd900863b8eb.png">

**Comment by lionelmace** [comment]
Fixed!
