### ISSUE TITLE
Coquille sur kubectl create

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#6]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/17337140/51544680-b3939c80-1e60-11e9-94ba-98cca2aa3aec.png">

1- rajouter le `a`: kubectl create -f deploy-app.y**a**ml
au lieu de : kubectl create -f deploy-app.yml

2- supprimer la seconde ligne avec: `

**Comment by lionelmace** [comment]
Replaced by `kubectl apply -f deploy-app.yml`
