### ISSUE TITLE
rajout d'une étape pour visualiser le dashboard kube avant le scale

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#9]
Avant de faire le scale à 3, 
taper: `kubectl get po`
et éventuellement ouvrir le dashboard Kube
<img width="920" alt="image" src="https://user-images.githubusercontent.com/17337140/51545994-7c72ba80-1e63-11e9-9178-86ecdd82d110.png">

**Comment by lionelmace** [comment]
fixed in step 1 of Lab 3
